# Generated by Django 4.2.5 on 2023-09-22 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='user_profile',
        ),
    ]
