# Generated by Django 4.2.5 on 2023-09-22 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_rename_user_message_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user_profile',
            new_name='user',
        ),
    ]
