# Generated by Django 4.2.5 on 2023-09-24 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_alter_userprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
